// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbRIv5womxeBNCfiy-JjviN9Ie2NuA1rw',
    appId: '1:447363356442:web:e5a93d0d8402c53ec4bea3',
    messagingSenderId: '447363356442',
    projectId: 'flutter-firebase-18081',
    authDomain: 'flutter-firebase-18081.firebaseapp.com',
    storageBucket: 'flutter-firebase-18081.appspot.com',
    measurementId: 'G-XN56WBJXK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBthJ_qDvEKcSH1ljiFpC3zlHXZl9AQVUc',
    appId: '1:447363356442:android:e2242108fc214a20c4bea3',
    messagingSenderId: '447363356442',
    projectId: 'flutter-firebase-18081',
    storageBucket: 'flutter-firebase-18081.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4PhE_x4VPNqrPxu0CBlpQNjFKVHFz8m0',
    appId: '1:447363356442:ios:66191117d8fba312c4bea3',
    messagingSenderId: '447363356442',
    projectId: 'flutter-firebase-18081',
    storageBucket: 'flutter-firebase-18081.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4PhE_x4VPNqrPxu0CBlpQNjFKVHFz8m0',
    appId: '1:447363356442:ios:515722d68b098a9dc4bea3',
    messagingSenderId: '447363356442',
    projectId: 'flutter-firebase-18081',
    storageBucket: 'flutter-firebase-18081.appspot.com',
    iosBundleId: 'flutter-firebase-18081',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbRIv5womxeBNCfiy-JjviN9Ie2NuA1rw',
    appId: '1:447363356442:web:d7f4aba11fb35d7cc4bea3',
    messagingSenderId: '447363356442',
    projectId: 'flutter-firebase-18081',
    authDomain: 'flutter-firebase-18081.firebaseapp.com',
    storageBucket: 'flutter-firebase-18081.appspot.com',
    measurementId: 'G-R4NY3NFN9Z',
  );
}
